### ISSUE TITLE
clipeus doesnt work on Samsung Galaxy s8+

### ISSUE THREAD

**Issue by zonkud** [x13a/Clipeus#2]
The app is without any feature. Tap, popup (clipboard cleaned), but the clipboard is still full.

**Comment by x13a** [comment]
I have the Samsung tablet with Android 12. Will check it.

**Comment by x13a** [comment]
On my end all is working as expected. Change keyboard for example to _gboard_, disable clipboard history.

**Comment by zonkud** [comment]
Other keyboard (florisboard) same result. The clipboard is not emptied. With my standard keyboard (samsung) I don’t find any function to disable history

**Comment by x13a** [comment]
What Android version are you using?

**Comment by zonkud** [comment]
Android 9 is running on the smartphone
I tested the app on a Samsung tablet with Android 11, unfortunately the clipboard is not emptied.

**Comment by x13a** [comment]
Sorry, but I have no idea. Manufacturers are modifying Android and sometime break some functionality. I have checked with _florisboard_ too and it is working as expected.

**Comment by zonkud** [comment]
That’s too bad. I will continue to test the app and monitor its development.
