### ISSUE TITLE
Question about giving the permission to auto-clear clipboard on screen off

### ISSUE THREAD

**Issue by resiehnnes** [x13a/Clipeus#3]
Could you please explain how to grant permission to add this optional functionality? I tried this command in terminal trough ADB but it did not worked:

adb shell pm grant me.lucky.clipeus android.permission.BIND_NOTIFICATION_LISTENER_SERVICE

Gives me:

Security exception: Package me.lucky.clipeus has not requested permission android.permission.BIND_NOTIFICATION_LISTENER_SERVICE

**Comment by x13a** [comment]
Settings > Notifications > Device and app notifications. If you could not
find, then you can install the app Vibe and press GOTO button.

**Comment by resiehnnes** [comment]
Ah thanks, turns out it is much easier than I thought. Maybe you could add a description for people like me who can't figure out what has to be done. I tested and it didn't worked right away but after couple of more tries it works now. Should I add this app to 'Battery optimization' ignore list, or it is not needed?

**Comment by x13a** [comment]
On Google Pixel I have not added it to any ignore lists, all is working
fine. But with other manufacturers it is better to do this.

**Comment by x13a** [comment]
closing on inactivity

**Comment by gbdomubpkm** [comment]
Hello @x13a 
Thanks a lot for this very useful app.
But i'm on AOSP 11 and I can't find how to activate this feature (auto clear).
Could you please clarify the procedure ?
Moreover, what is this app called 'vibe' ? what is the developer and where is the app ? I  don't find it if it is necessary to use it.
Thanks in advance.
(and I will see too a widget for this great app if there isn't currently 😉).

**Comment by x13a** [comment]
Hey @gbdomubpkm ,

You can use the app [Vibe](https://github.com/x13a/Vibe) to open `Settings > Notifications > Device & app notifications` for you. Install it and press the bottom button. It is not necessary to use it, if you do not need it.

**Comment by gbdomubpkm** [comment]
I am surprised to go through another app  (Vibe) to activate this feature, but it works perfectly indeed. Thanks @x13a
