### ISSUE TITLE
Shortcut to open device & app notifications settings

### ISSUE THREAD

**Issue by x13a** [x13a/Clipeus#4]

**Comment by gbdomubpkm** [comment]
Hello.
Thanks for this.
Maybe i didn't exactly understand what you mean by 'long tap' on the app icon, but it doesn't seem to work with discreet launcher (Vincent Falzon) or it can't work with this launcher.
I get this:
![Clipeus long Tap](https://user-images.githubusercontent.com/50362604/181186427-164dd0ff-df6d-43bc-bf3d-10ea3efcbfb0.png)
I found another solution with an app called Shortcut Maker (Rushikesh Kamewar) to get the shortcut.

**Comment by x13a** [comment]
It seems that your launcher do not support them. Often it look like this (on the top of Chrome):

![](https://developer.android.com/static/images/guide/topics/ui/shortcuts/pinned-shortcuts.png)
